service: psl-reduce

custom:
  bucket: ${file(./config.json):bucket}

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "arn:aws:s3:::*"
  region: us-west-1

functions:
  process:
    handler: handler.process
    events:
      - existingS3:
          bucket: ${self:custom.bucket}
          events:
            - s3:ObjectCreated:*

plugins:
  serverless-plugin-existing-s3
